### ISSUE TITLE
[Question] Possible change of the Attachments session no link to text file?

### ISSUE THREAD

**Issue by xyngfei** [cenfun/monocart-reporter#58]
The current HTML behavior will display the <div> to display all text content

![image](https://github.com/cenfun/monocart-reporter/assets/17619539/83aad56f-a1a9-4baf-90b9-7f2dcca840de)

Would it possible for monocart can do the same behavior, rather than provide a text file?
![image](https://github.com/cenfun/monocart-reporter/assets/17619539/db334363-b67d-4666-9085-4b228e16b2f5)

**Comment by cenfun** [comment]
please try new version monocart-reporter@1.7.8

**Comment by xyngfei** [comment]
appreciate your fast response, but I have some issues with running version 1.7.8

<img width="1207" alt="image" src="https://github.com/cenfun/monocart-reporter/assets/17619539/7a13c47b-fbbc-4661-9495-88f6fd8a9e7f">

let say i have the code as below


```
            test.info().attach("application/json: ", {
              contentType: "application/json",
              body: `{ "Name": "cenfun", "Rank": 1 }`,
            });
            test.info().attach("text/plain: ", {
              contentType: "text/plain",
              body: `monocart is the best playwright reporter`,
            });
```

**Comment by xyngfei** [comment]
I know the root cause of the issue, if there is a "/", it will throw the exception.
Meanwhile, i m still seeing the same behaviour

![image](https://github.com/cenfun/monocart-reporter/assets/17619539/c14cee50-c659-4826-b2e7-801b6d640c95)

the existing HTML reporter will also link to the file, somehow overwrite the existing behaviour
![image](https://github.com/cenfun/monocart-reporter/assets/17619539/9b594c32-e285-4a2d-a25c-c804e39999ce)

**Comment by cenfun** [comment]
yes, your filename is invalid. see https://playwright.dev/docs/api/class-testinfo#test-info-attach

```
await testInfo.attach(name, options);
```
name:
Attachment name. The name will also be sanitized and used as the prefix of file name when saving to disk.

```
test.info().attach("your_filename", {
              contentType: "application/json",
              body: `{ "Name": "cenfun", "Rank": 1 }`,
            });
```
currently, there is no illegal character filtering for monocart reporter.

**Comment by cenfun** [comment]
please try monocart-reporter@1.7.9, the error should be fixed

**Comment by xyngfei** [comment]
it fixed the illegal character filtering issue, but the attachment part, it is still showing to link a file, and modify the existing html behaviour, possible to take a look again?

**Comment by cenfun** [comment]
got your questions, you want to show the content of custom attachment file like HTML report but not a link?
![image](https://github.com/cenfun/monocart-reporter/assets/334577/fec6b49c-b1ab-4962-8be0-2ee2b3d848d9)
let me think how to implementation, just reopen the issue.

**Comment by xyngfei** [comment]
the current advantage of open as a text file, i can format the JSON content, but if i have multiple APIs, very painful to open 1 by open 

![image](https://github.com/cenfun/monocart-reporter/assets/17619539/085f0ab0-1b10-44c6-acd0-5dcccc34aa85)

**Comment by xyngfei** [comment]
yeah, correct, bcos if I am using `console.info`, it will mess out the list reporter via the terminal. Therefore, I am using attach to include all api url, request body, response header and response body

**Comment by cenfun** [comment]
Please update version to monocart-reporter@1.7.10
test some cases and it should works now.
```
test.info().attach('application/json stringify:', {
        contentType: 'application/json',
        body: JSON.stringify({
            Name: 'cenfun',
            Text: 'long text long text long text long text long text long text'
        }, null, 4)
    });

    test.info().attach('json:', {
        contentType: 'application/json',
        body: '{ "Name": "cenfun", Text: "long text long text long text long text long text long text" }'
    });

    test.info().attach('text:', {
        contentType: 'text/plain',
        body: 'long text long text long text long text long text long text'
    });

    test.info().attach('text/plain:', {
        contentType: 'text/plain',
        body: `monocart reporter,
        playwright test reporter`
    });

    test.info().attach('text/markdown:', {
        contentType: 'text/markdown',
        body: `### monocart reporter
        - playwright test reporter
        - html reporter`
    });
```
![image](https://github.com/cenfun/monocart-reporter/assets/334577/02ba2c10-9355-4182-a44a-41806427b3d5)

specially, markdown format will be supported too.

**Comment by xyngfei** [comment]
@cenfun you are really impressive, especially with your fast response and resolution + additional support for MD, It works as expected.

btw, the link is not working, need your help to look into it
https://cenfun.github.io/monocart-reporter/network-1a18723ee59b36867898/index.html

OMG, the sample [HAR](https://cenfun.github.io/monocart-reporter/network-da7f5b4cceb1e6280782/index.html) is more than what I expected. Let me explore it first. Meanwhile, this issue should be resolved for now.

Once again, I will continue to support this awesome project
